
server:
  port: 8093
  contextPath: /orders/api

logging:
  level:
    org.orders.controllers: INFO
    
entitymanager:
    packagesToScan: org.orders
spring:
    application:
        name: OrdersRS
    datasource:
        driverClassName: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@windows10.server.com:1521:orcl
        username: OE
        password: oe
        initialize: true
        testWhileIdle: 1
        validationQuery: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.Oracle10gDialect
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

